---
title: Основы подготовки и визуализации данных на языке R
description: Вводная информация 
---




R – ведущая статистическая программа для анализа данных на сегодняшний день, визуализация данных, моделирование и работы с GIS. Её главное достоинство – после освоения базовых принципов R намного проще в использовании, чем другие инструменты. Программа R удобна для работы с большим массивом данных, их объединение из разных таблиц, проводить разнообразные манипуляции над данными. В рамках семинара вы получите начальные знания о работе программы R: писать скрипты, загружать таблицы и пакеты, простым манипуляциям над данными и таблицам, строить простые и более сложные графики, находить в интернете необходимую информации.


Для успешного прохождения курса, Вы должны понимать, что примерно 20% времени семинара составляют лекции, и **80%– самостоятельные занятия: выполнение домашнего задания + освоение материала**. В конце участники работают со своими данными – индивидуальные проекты, чтобы закрепить полученные знания наилучшим образом.
Занятия бесплатные. По окончании всем участникам семинара, защитившим *индивидуальный проект*, выдается сертификат с указанием наименования курса и количества часов.

Внимание! Курс насыщенный и сложный! Если Вы в программе R новичок, учтите, что курс потребует от Вас существенных временных затрат. Возможно, Вам поможет прохождение вот [этого бесплатного русскоязычного курса](https://stepik.org/course/129/promo#toc). 





 
## контакты

- Анна Сергеевна Мухачева - siam83[]mail.ru
- Хайтов Вадим Михайлович - polydora[]rambler.ru
