---
title: Материалы для занятий на семинаре
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    highlight: haddock
    include:
      after_body: _footer.html
    css: my_styles.css
---

# **Первые действия**
- [Установка R и RStudio на компьютеры под OC Windows](Intro_to_R_first_steps.html)
- [Установка R и RStudio на компьютеры под OC Linux (тестировнао на Ubuntu 22.04.3)](https://drive.google.com/file/d/1AjBSoWZ3DmXt-7Rv88jfCbQNm1M1aEmM/view?usp=sharing)


# **Книги**

- [Визуализация даных с помощью ggplot2](https://drive.google.com/file/d/1lGfc0yjIYHBYst5HYuNBiSuQ9I-kXoZ5/view?usp=sharing) 

- [Наглядная статистика. Используем R!](https://drive.google.com/file/d/1HD2X36Lfy9hiIaBTzhQ57EsToLh2ShG7/view?usp=drive_link)

- [Статистическая обработка данных на языке R](https://drive.google.com/file/d/1GVYorXdbCyx5ypy1cZ_rIhBf4dR_xR_2/view?usp=drive_link)

**Дополнительно:** Некоторые пособия (на английском языке) вы найдете на стрнаичке "Полезности" нашего сайта.

<br>
<br>

# **Материалы лекций**
<br>

## *Лекция 1.* Знакомство с R 

- [Скрипт](https://drive.google.com/file/d/14utYHyblQ3R-12m6XFbKO9tKAOG6F1tD/view?usp=drive_link)

- [Домашнее задание](https://docs.google.com/document/d/1e9xi5rzaFdD_qoZ0U1O4greW9TuruF4M/edit?usp=drive_link&ouid=104073765878946580320&rtpof=true&sd=true)

- [Видео семинара](https://drive.google.com/file/d/15uYiayOunjzZNuo3I95HG6k63x3MHllf/view?usp=drive_link)

- [Видео о том, как работать с RStudio в Облаке](https://drive.google.com/file/d/1EbJvC8YtZISA_vS4JET0yV5oqzeBFTUe/view?usp=drive_link)


## *Лекция 2.* Работа с таблицами

- [Скрипт](https://drive.google.com/file/d/1sbENZKPvbNUxI4gX-vw4kDZFvKHszR4r/view?usp=drive_link)

- [Домашнее задание](https://docs.google.com/document/d/1SQvzqIxSQ27gjA-_q0SqO0duyaT2nFOl/edit?usp=drive_link&ouid=104073765878946580320&rtpof=true&sd=true)

- [Видео семинара](https://drive.google.com/file/d/11xTvPoJdTQ1fWdAWmsK_GAdBWSDNDTPY/view?usp=drive_link)


## *Лекция 3.* Работа с базовой графикой

- [Скрипт](https://drive.google.com/file/d/1umsAQh_bmEme3nRjDFNsscnLVPILl2BD/view?usp=drive_link)

- [Домашнее задание](https://docs.google.com/document/d/1Bnb6Cd25O3HxrTE1YXVky1stsDZ7mwvU/edit?usp=drive_link&ouid=104073765878946580320&rtpof=true&sd=true)


- [Видео семинара](https://drive.google.com/file/d/1yzgzbfV7C5LjHf9ZcW1vWA8RyfFK_qCv/view?usp=drive_link)



## *Лекция 4.* Визуализация данных с помощью пакета `ggplot2`

- [Презентация с объяснением основ tidy data](Pres_tidy_data.html)

- [Пример данных в широком и длинном формате](data/Birds_count_example.xlsx)



- [Презентация с объяснением основ работы в `ggplot2`](Pres_intro_ggplot.html)
- [Скрипт](intro_ggplot.R)
- [Данные для работы](data/fev.xls)

- [Домашнее задание](Home_Work_ggplot.html)
- [Данные для домашней работы](data/hydrology_2022.xls)


- [Видео семинара](https://drive.google.com/file/d/16iEdmxlrEZvNKceSoJSFFhPYvBUkb9w8/view?usp=drive_link)

<!-- - [Скрипт с решением для домашнего задания по `ggplot`](Home_Work_ggplot_Solution.R) -->

## *Лекция 5.* Работа с данными

- [Скрипт](https://drive.google.com/file/d/1m4JmZ08WerFwTjz9SffdLGV7wot4ja6n/view?usp=drive_link)
- [Данные для работы](https://drive.google.com/file/d/1LHik6QsUSfSvjCvXrVjsOLAa-oAx5m1u/view?usp=drive_link)
- [Домашнее задание](https://docs.google.com/document/d/1LS5IpHuRJ7fVXKS7ryaf53ZF4EsnLwAF/edit?usp=drive_link&ouid=104073765878946580320&rtpof=true&sd=true)
- [Данные для домашней работы № 1](https://drive.google.com/file/d/1qFY5BnUChUevet9sX4ggSKu9sPy_za0d/view?usp=drive_link)
- [Данные для домашней работы №2](https://docs.google.com/document/d/1LS5IpHuRJ7fVXKS7ryaf53ZF4EsnLwAF/edit?usp=drive_link&ouid=104073765878946580320&rtpof=true&sd=true)
- [Видео семинара](https://drive.google.com/file/d/1GkSGB3yLR0meEyQgUfBMXPc-UFXLw3Vm/view?usp=drive_link)


## *Лекция 6.* Встроенные функции для работы с данными

- [Скрипт](https://drive.google.com/file/d/1eCvxEE89uqMvccfCLPdcEBL0r9MGnkQf/view?usp=drive_link)
- [Видео семинара](https://drive.google.com/file/d/10m1Ab_QRNG4ZXcXzhWHHhO1qjD9w1sOc/view?usp=drive_link)
<br>
<!-- - [Домашнее задание]() -->


## *Лекция 7.* Пакеты `tidyr` и `dplyr`
- [Скрипт](https://drive.google.com/file/d/1igUuD4_rWM_cuyy2PZCszrjjITitPHcV/view?usp=drive_link)
- [Датасет 1](https://drive.google.com/file/d/1rEZzoh_7QFDgNzXFPUSqJZo-3cwfwUQ-/view?usp=drive_link)
- [Датасет 2](https://drive.google.com/file/d/12BqJZhSt7TzhamvqbG3TUG2Fi8KDA3_P/view?usp=drive_link)
- [Датасет 3](https://drive.google.com/file/d/1WAONxm4E6ExU3Xr2C1qg1016UPMfILr_/view?usp=drive_link)
- [Домашнее задание](https://docs.google.com/document/d/1wyodCuBz0cm-Rl8dEjeCZOHxTOD1zWUW/edit?usp=drive_link&ouid=104073765878946580320&rtpof=true&sd=true)
<br>


## *Лекция 8.* Основы литературного программирования. Часть 1: Язык разметки страниц `R Markdown`

<br>
<!-- - [Скрипт]() -->
<!-- - [Домашнее задание]() -->


## *Лекция 9.* Основы литературного программирования. Часть 2: Работа с таблицами в R Markdown и создание отчетов в формате Word.

<br>
<!-- - [Скрипт]() -->
<!-- - [Домашнее задание]() -->

# **Проекты** 





