---
title: Расписание занятий
output:
  html_document:
    toc: false
    toc_float:
      collapsed: false
    highlight: haddock
    css: my_styles.css
---

| **Дата** | **Время**  по Владивостоку  | **Содержание**                                                                                                                                                                                                                                                |
|----------|-------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 26.03    | 15:00-17.00 | О программе R.  Простые функции в R. Класс (типы) данных  Загрузка пакетов                                                                                                                                                                                    |
| 29.03    | 15:00-17.00 | Работа с таблицами Сохранение/Загрузка созданной в R таблицы                                                                                                                                                                                                  |
| 2.04     | 15:00-17.00 | Работа с базовой графикой (plot, hist, point)                                                                                                                                                                                                                 |
| 5.04     | 15:00-17.00 | Работа с графикой ggplot2                                                                                                                                                                                                                                     |
| 9.04     | 15:00-17.00 | Работа с данными: сортировать (ordered), переименовать столбцы и строки, исправить ошибки в строках (str_replace, str_extract из пакета stringr), убрать пропущенные данные (na.omit и complete.cases ), выбросы и тд.                                        |
| 12.04    | 15:00-17.00 | Встроенные функции: subset, gep,  aggregate, семейства apply, Ifelse. Фильтр данных, исправление ошибок в строках, агрегировать данные по заданным параметрам, логические операции «если, то»                                                                 |
| 16.04    | 15:00-17.00 | Пакеты: dplyr, tidyr. Основные функции: поменять столбцы местами, выбрать определенные столбцы по названиям, задать фильтр для данных, разделить/соединить данные по заданным знакам, сделать расчеты по формулам, поворот таблиц,                            |
| 19.04    |             | Пакеты: lubridate (работа с датами), tidyverse -пакет, который содержит, некоторые пройденные пакет.  R Markdown, Rmd: создание таксовых документов, которые включают в себя текст, код, картинки и тд. И скомпилировать в различные документы (Word, PDF).   |
| 23.04    |             | Дополнительное занятие, вопросы от участников                                                                                                                                                                                                                 |